name: 🚀 Polyglot Journey CI

on:
  push:
    branches: [ main ]
    paths:
      - 'S1-Mastery/**'
      - 'S2-Expansion/**'
      - 'Base Camp/templates/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'S1-Mastery/**'

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Detect which project folders changed
      - name: Get Changed Projects
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            S1-Mastery/**
            Base Camp/templates/**

      # 2. Static Analysis (Linting)
      - name: Lint Backend (Flake8)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # 3. Dynamic Docker Testing
      - name: Run Project Tests
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          # Use dummy values for CI environment
          DEBUG: True
          SECRET_KEY: ci-test-key
          DB_NAME: challenge_db
          DB_USER: user
          DB_PASSWORD: password
          DB_HOST: db
          DB_PORT: 5432
        run: |
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ -f "$dir/docker-compose.yml" ]; then
              echo "🛠️ Testing Project: $dir"
              cd "$dir"
              
              # Start the stack
              docker-compose up -d
              
              # Wait for Postgres to be ready (using the nc check from your compose file)
              docker-compose exec -T backend sh -c "while ! nc -z db 5432; do sleep 1; done"
              
              # Execute Django Tests
              docker-compose exec -T backend python manage.py test
              
              # Cleanup
              docker-compose down
              cd -
            fi
          done